version: '3.6'

services:
  own-website-api:
    image: costanzopa/own-website-api
    container_name: own-website-api
    networks:
      - own-website-api-network
    environment:
      - PORT=8080
      - HOST='localhost'
      - DB_URL="mongodb://own-website-api-db:27017/own-website-api-db"
    depends_on:
      - own-website-api-db
    ports:
      - '8080:8080'
    volumes:
      - .:/app

  own-website-api-db:
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    container_name: own-website-api-db
    networks:
      - own-website-api-network
    volumes:
      - ./data:/data/db

networks:
  own-website-api-network:
